### ISSUE TITLE
DelayedOperationHandler & Emit

### ISSUE THREAD

**Issue by StanFrag** [Lusito/typed-ecstasy#1]
Hey Lusito,

I have some issues when i try to use your ECS engine.

![screen](https://user-images.githubusercontent.com/8088765/33939736-938c6bee-e00c-11e7-8ef7-a44b30d0a6f9.png)

Thanks for your job anyways ;)

**Comment by Lusito** [comment]
@StanFrag: What TypeScript compiler are you using? I'm not sure if the Angular compiler is up to date with the latest typescript.

I'm also a bit confused about the output, as the line numbers clearly don't match the shown snippets.
Good thing tho is, that the code at the mentioned line numbers match up with the error messages. I think it should be possible to fix those for you.

**Comment by Lusito** [comment]
I have added possible fixes in the respective development branches:
https://github.com/Lusito/typed-ecstasy/tree/develop
https://github.com/Lusito/typed-signals/tree/develop

If you could try hot patching them to see if it works, that would be nice.
I will publish a new version once I know all compiler errors are fixed (I have a feeling there will be more)

Thanks!
