### ISSUE TITLE
System.setEnabled(false) doesn't trigger `onDisable` life-cycle method

### ISSUE THREAD

**Issue by MadMed677** [Lusito/typed-ecstasy#8]
## Description
[By the documentation](https://lusito.github.io/typed-ecstasy/guide/core/entitysystem.html#enabling-disabling-entitysystems-without-removing-them), the `onDisable` life-cycle method should be called in two cases
1. When the system is `removed`
2. When the system is `disabled`

But I've realised that this life-cycle (LC) method doesn't triggers on `setEnabled(false)` only on `engine.systems.remove()`

## How to reproduce
1. Add any system into the engine (`engine.systems.add(MySystem)`)
2. Add breakpoint or console.log inside system's `onDisable` LC method
3. Retrieve and trigger `const mySystem = engine.systems.get(MySystem)!` `mySystem.setEnabled(false)` - no debug / console.log event

## How it should work
On step `3` it should call debug/console.log

**Comment by Lusito** [comment]
Thanks for the report. Fix release will be available soon

**Comment by Lusito** [comment]
Please check out the new documentation as well, as the situations have been adjusted a bit to avoid duplicate/confusing calls:
https://lusito.github.io/typed-ecstasy/api/classes/AbstractSystem.html#ondisable
